Remove falsy values from input
fragaria/address-formatter pull request #229
Opened 2020-10-21 15:02 UTC by StephanGeorg

2020-10-24 14:24 UTC, JirkaChadima requested changes
Thanks for the contribution! Apart from one small nit, I have one bigger request. Can you add a test case for this behaviour? Thank you!

2020-10-24 14:24 UTC, JirkaChadima commented on src/index.js
> +  if (value) acc[key] = value;
Can you wrap this into the curly braces? This shorthand `if` syntax is less explicit.

2020-10-26 11:05 UTC, StephanGeorg commented
Turns out that the bug was in the `normalizeComponentKeys` only.

2020-10-28 16:33 UTC, merged

2020-10-28 16:33 UTC, JirkaChadima commented
Thanks!